from ollama import Client

from app.config.settings import settings
from app.models.document import Document
from app.utils.logger import logger

from .prompt import PERSONAL_INFO_PROMPT


class OllamaExtractor:
    """
    Extract personal information from a resume using an Ollama model.
    """

    def __init__(self):
        self.client = Client(host=settings.OLLAMA_BASE_URL)
        self.model = settings.OLLAMA_MODEL

    def extract(self, document: Document) -> str:
        """
        Send the resume text to Ollama and return the raw JSON response.

        Args:
            document: Parsed resume document.

        Returns:
            Raw JSON string generated by the model.
        """
        logger.info('Ollama has satarted')

        prompt = PERSONAL_INFO_PROMPT.format(
            resume=document.markdown
        )

        response = self.client.chat(
            model=self.model,
            messages=[
                {
                    "role": "user",
                    "content": prompt,
                }
            ],
        )
        logger.info('Got the response by ollama')

        return response["message"]["content"].strip()